name: Jest CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - name: Deploy
      if: github.event_name == 'push'
      env:
        URL_RENDER_DEPLOY_HOOK: ${{ secrets.URL_RENDER_DEPLOY_HOOK }}
      run: |
        curl --fail-with-body $URL_RENDER_DEPLOY_HOOK
